### PR TITLE
Get rid of MIN_WORD_LENGTH_BOUNDRY in favor of SETTING_DEFAULT_MIN_WORD_LENGTH

### LINKED ISSUE #37: Unwanted MIN_WORD_LENGTH_BOUNDRY
The `minWordLength` setting is limited by `MIN_WORD_LENGTH_BOUNDRY` (https://github.com/ytiurin/hyphen/blob/master/src/create-hyphenator.js#L64-L67).
My use-case requires hyphenating all the words (I know what I am doing, performance is not important) but this limitation renders the library useless for my case.

Please remove `MIN_WORD_LENGTH_BOUNDRY`.

### PR DESCRIPTION
**Pull request by kamilmielnik**
Closes https://github.com/ytiurin/hyphen/issues/37

### CODE REVIEW

**Review by krisztianb — CHANGES_REQUESTED** [review]
Unfortunately the same code is there twice in the file. So we will have to update both occurrences.

**Comment by kamilmielnik** [comment]
@krisztianb 

I don't think so.
Are you referring to these lines: https://github.com/ytiurin/hyphen/blob/master/src/create-hyphenator.js#L93-L96?
I believe they're not doing _the same_ thing.

With the current state of this PR, this code will work as expected: https://github.com/ytiurin/hyphen/issues/37#issuecomment-812842963

**Comment by krisztianb** [comment]
Sorry. It looks like you are right.

**Review by krisztianb — APPROVED** [review]

**Comment by ytiurin** [comment]
@kamilmielnik @krisztianb Thank you, guys, for supporting this!

**Pull request merged**
